name: 텔레그램 업무 알림

on:
  schedule:
    # 매분 실행
    - cron: '* * * * *'

  workflow_dispatch:

permissions:
  contents: write

jobs:
  telegram-alert:
    runs-on: ubuntu-latest

    steps:

      - name: 체크아웃
        uses: actions/checkout@v4

      - name: 파이썬 설정
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: 텔레그램 알림 보내기
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: python bot.py

      - name: 전송된 로그 저장
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add sent_log.json
            git commit -m "전송된 로그 업데이트"
            git push
          fi
